In [82]:
import pandas as pd
import numpy as np

Import the csv, do not skip blanks

In [83]:
input = pd.read_csv("input.txt", sep = " ",header= None, names= ["opponent","response"])
df = pd.DataFrame(input)

"The first column is what your opponent is going to play: A for Rock, B for Paper, and C for Scissors. The second column--" Suddenly, the Elf is called away to help with someone's tent.

The second column, you reason, must be what you should play in response: X for Rock, Y for Paper, and Z for Scissors. Winning every time would be suspicious, so the responses must have been carefully chosen.

The winner of the whole tournament is the player with the highest score. Your total score is the sum of your scores for each round.

Defining the conditions for the score of shape selection inside a function

In [84]:
def shape_score(shape):
    if shape == 'X':
        return 1
    elif shape == 'Y':
        return 2
    elif shape == 'Z':
        return 3

Assigning score per row for selection

In [85]:
df['selectedscore'] = df['response'].apply(shape_score) 
df

     opponent response  selectedscore
0           A        X              1
1           C        X              1
2           C        X              1
3           C        X              1
4           B        Y              2
...       ...      ...            ...
2495        B        X              1
2496        C        Z              3
2497        A        X              1
2498        B        X              1
2499        C        X              1

[2500 rows x 3 columns]

Mapping opponent and response actions in a dictionary

In [86]:
opponent_dict = {  "A": "rock",  "B": "paper",  "C": "scissors"}
response_dict = {  "X": "rock",  "Y": "paper",  "Z": "scissors"}

Replace response by rock, paper, scissors.

In [87]:
df

     opponent response  selectedscore
0           A        X              1
1           C        X              1
2           C        X              1
3           C        X              1
4           B        Y              2
...       ...      ...            ...
2495        B        X              1
2496        C        Z              3
2497        A        X              1
2498        B        X              1
2499        C        X              1

[2500 rows x 3 columns]

In [88]:
df['opponent_action'] = df['opponent'].map(opponent_dict)
df['response_action'] = df['response'].map(response_dict)
df

     opponent response  selectedscore opponent_action response_action
0           A        X              1            rock            rock
1           C        X              1        scissors            rock
2           C        X              1        scissors            rock
3           C        X              1        scissors            rock
4           B        Y              2           paper           paper
...       ...      ...            ...             ...             ...
2495        B        X              1           paper            rock
2496        C        Z              3        scissors        scissors
2497        A        X              1            rock            rock
2498        B        X              1           paper            rock
2499        C        X              1        scissors            rock

[2500 rows x 5 columns]

Function with the game conditions. The score for a single round is the score for the shape you selected (1 for Rock, 2 for Paper, and 3 for Scissors) plus the score for the outcome of the round (0 if you lost, 3 if the round was a draw, and 6 if you won).

In [89]:
def rps_score(opponent, response):
    if response == opponent:
        return 3
    elif response == "rock":
        if opponent == "scissors":
            return 6
        else:
            return 0
    elif response == "paper":
        if opponent == "rock":
            return 6
        else:
            return 0
    elif response == "scissors":
        if opponent == "paper":
            return 6
        else:
            return 0

Assigning score per row with win conditions

In [95]:
df['rps_score']= df.apply(lambda x: rps_score(x['opponent_action'], x['response_action']), axis=1)
df

,opponent,response,selectedscore,opponent_action,response_action,rps_score
0,A,X,1,rock,rock,3
1,C,X,1,scissors,rock,6
2,C,X,1,scissors,rock,6
3,C,X,1,scissors,rock,6
4,B,Y,2,paper,paper,3
...,...,...,...,...,...,...
2495,B,X,1,paper,rock,0
2496,C,Z,3,scissors,scissors,3
2497,A,X,1,rock,rock,3
2498,B,X,1,paper,rock,0
2499,C,X,1,scissors,rock,6

Output 1: Sum of scores

In [96]:
result1 = np.sum(df['selectedscore']) + np.sum(df['rps_score'])
print(result1)

11063

Output 2:

"Anyway, the second column says how the round needs to end: X means you need to lose, Y means you need to end the round in a draw, and Z means you need to win. Good luck!"

In [92]:
df

,opponent,response,selectedscore,opponent_action,response_action,rps_score
0,A,X,1,rock,rock,None
1,C,X,1,scissors,rock,None
2,C,X,1,scissors,rock,None
3,C,X,1,scissors,rock,None
4,B,Y,2,paper,paper,None
...,...,...,...,...,...,...
2495,B,X,1,paper,rock,None
2496,C,Z,3,scissors,scissors,None
2497,A,X,1,rock,rock,None
2498,B,X,1,paper,rock,None
2499,C,X,1,scissors,rock,None

In [103]:
response_result_dict = {  "X": "loss",  "Y": "draw",  "Z": "win"}
df['result'] = df['response'].map(response_result_dict)
df

,opponent,response,selectedscore,opponent_action,response_action,rps_score,result
0,A,X,1,rock,None,3,loss
1,C,X,1,scissors,None,6,loss
2,C,X,1,scissors,None,6,loss
3,C,X,1,scissors,None,6,loss
4,B,Y,2,paper,paper,3,draw
...,...,...,...,...,...,...,...
2495,B,X,1,paper,None,0,loss
2496,C,Z,3,scissors,rock,3,win
2497,A,X,1,rock,None,3,loss
2498,B,X,1,paper,None,0,loss
2499,C,X,1,scissors,None,6,loss

LOSE:
opp: rock > scissors
opp: scissors > paper
opp: paper > rock

WIN :
opp: rock > paper
opp: scissors > rock
opp: paper > scissors

draw :
opp: rock > rock
opp: scissors > scissors
opp: paper > paper

In [104]:
def response_action(opponent_action, result):
    if result == "draw":
        return opponent_action
    elif result == "loss":
        if opponent_action == "rock":
            return "scissors"
        elif opponent_action == "scissors":
            return "paper"
        else:
            return "rock"
    elif result == "win":
        if opponent_action == "rock":
            return "paper"
        elif opponent_action == "scissors":
            return "rock"
        else:
            return "scissors"

In [105]:
df['response_action']= df.apply(lambda x: response_action(x['opponent_action'], x['result']), axis=1)
df

,opponent,response,selectedscore,opponent_action,response_action,rps_score,result
0,A,X,1,rock,scissors,3,loss
1,C,X,1,scissors,paper,6,loss
2,C,X,1,scissors,paper,6,loss
3,C,X,1,scissors,paper,6,loss
4,B,Y,2,paper,paper,3,draw
...,...,...,...,...,...,...,...
2495,B,X,1,paper,rock,0,loss
2496,C,Z,3,scissors,rock,3,win
2497,A,X,1,rock,scissors,3,loss
2498,B,X,1,paper,rock,0,loss
2499,C,X,1,scissors,paper,6,loss

In [106]:
def shape_score2(shape):
    if shape == 'rock':
        return 1
    elif shape == 'paper':
        return 2
    elif shape == 'scissors':
        return 3

In [108]:
df['selectedscore2'] = df['response_action'].apply(shape_score2) 
df

,opponent,response,selectedscore,opponent_action,response_action,rps_score,result,selectedscore2
0,A,X,1,rock,scissors,3,loss,3
1,C,X,1,scissors,paper,6,loss,2
2,C,X,1,scissors,paper,6,loss,2
3,C,X,1,scissors,paper,6,loss,2
4,B,Y,2,paper,paper,3,draw,2
...,...,...,...,...,...,...,...,...
2495,B,X,1,paper,rock,0,loss,1
2496,C,Z,3,scissors,rock,3,win,1
2497,A,X,1,rock,scissors,3,loss,3
2498,B,X,1,paper,rock,0,loss,1
2499,C,X,1,scissors,paper,6,loss,2

In [110]:
df['rps_score2']= df.apply(lambda x: rps_score(x['opponent_action'], x['response_action']), axis=1)
df

,opponent,response,selectedscore,opponent_action,response_action,rps_score,result,selectedscore2,rps_score2
0,A,X,1,rock,scissors,3,loss,3,0
1,C,X,1,scissors,paper,6,loss,2,0
2,C,X,1,scissors,paper,6,loss,2,0
3,C,X,1,scissors,paper,6,loss,2,0
4,B,Y,2,paper,paper,3,draw,2,3
...,...,...,...,...,...,...,...,...,...
2495,B,X,1,paper,rock,0,loss,1,0
2496,C,Z,3,scissors,rock,3,win,1,6
2497,A,X,1,rock,scissors,3,loss,3,0
2498,B,X,1,paper,rock,0,loss,1,0
2499,C,X,1,scissors,paper,6,loss,2,0

In [111]:
result2 = np.sum(df['selectedscore2']) + np.sum(df['rps_score2'])
print(result2)

10349